export default {
   items: JSON.parse(localStorage.getItem('items') as string) || [],
   itemsId: JSON.parse(localStorage.getItem('items-id') as string) || [],
   language: JSON.parse(localStorage.getItem('language') as string) || 'nl',
   singleItem: [],
   paginationNumbers: [],
   paginatedItems: [],
   relatedItems: [],
   siteMap: [],
   maxRecordsNumber: '30',
   recordsPerPage: 10,
   APIkey: 'iOQQBTgH',
   loading: false,
   error: '',
   route: '',
};
